---

services: "docker"

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - touch rails/.env.production node/.env.production

  - cd flask
  - docker-compose up --build -d
  - sleep 30
  - >
    curl -s -o /dev/null -w "%{http_code}" http://localhost:8000
    | grep -q '200'
    && (echo 'HTTP test: pass' && exit 0)
    || (echo 'HTTP test: fail' && exit 1)
  - docker-compose down -v

  - cd ../rails
  - docker-compose up --build -d
  - sleep 30
  - docker-compose exec web rails db:create
  - sleep 10
  - >
    curl -s -o /dev/null -w "%{http_code}" http://localhost:8000
    | grep -q '200'
    && (echo 'HTTP test: pass' && exit 0)
    || (echo 'HTTP test: fail' && exit 1)
  - docker-compose down -v

  - cd ../node
  - docker-compose up --build -d
  - sleep 30
  - >
    curl -s -o /dev/null -w "%{http_code}" http://localhost:8000
    | grep -q '200'
    && (echo 'HTTP test: pass' && exit 0)
    || (echo 'HTTP test: fail' && exit 1)
  - docker-compose down -v

  - cd ../phoenix
  - docker-compose up --build -d
  - sleep 30
  - >
    curl -s -o /dev/null -w "%{http_code}" http://localhost:8000
    | grep -q '200'
    && (echo 'HTTP test: pass' && exit 0)
    || (echo 'HTTP test: fail' && exit 1)
  - docker-compose down -v

  - cd ../webpack
  - docker-compose build
  - docker-compose run webpack yarn run build
  - >
    cat public/css/app.css
    && (echo 'CSS file test: pass' && exit 0)
    || (echo 'CSS file test: fail' && exit 1)
  - >
    cat public/js/app.js
    && (echo 'JS file test: pass' && exit 0)
    || (echo 'JS file test: fail' && exit 1)
  - docker-compose down -v
