version: "3.7"

services:
  mariadb:
    env_file:
      - ".env"
    image: "mariadb:10.3"
    volumes:
      - "mariadb:/var/lib/mysql"

  redis:
    image: "redis:5.0-alpine"
    volumes:
      - "redis:/data"

  webpack:
    build:
      context: "."
      dockerfile: "Dockerfile.webpack"
    command: "yarn run watch"
    volumes:
      - ".:/app"

  web:
    build:
      context: "."
    depends_on:
      - "mariadb"
      - "redis"
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    volumes:
      - ".:/var/www/html"

volumes:
  mariadb: {}
  redis: {}
