version: "3.7"

services:

  mariadb:
    image: "mariadb:10.3"
    env_file:
      - ".env"
    volumes:
      - "mariadb:/var/lib/mysql"

  redis:
    image: "redis:4.0-alpine"
    volumes:
      - "redis:/data"

  webpack:
    build:
      context: "."
      dockerfile: "Dockerfile.webpack"
    command: yarn prod
    volumes:
      - ".:/app"

  web:
    build:
      context: "."
    depends_on:
      - "mariadb"
      - "redis"
    env_file:
      - ".env"
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html"

volumes:
  mariadb: {}
  redis: {}
