FROM node:10.12-alpine
LABEL maintainer="Niko Heikkilä <yo@nikoheikkila.fi>"

ENV NODE_ENV=development

RUN npm install -g yarn

WORKDIR /app

COPY package.json webpack.mix.js *yarn* ./
COPY resources/js/ ./resources/js/
COPY resources/sass/ ./resources/sass/

RUN yarn install

COPY . .

CMD ["yarn", "run", "watch"]
