FROM node:10.12-slim

RUN npm install -g yarn

WORKDIR /app

COPY package.json webpack.mix.js *yarn* ./
COPY resources/js/ ./resources/js/
COPY resources/sass/ ./resources/sass/

RUN yarn install

COPY . .

LABEL maintainer="Niko Heikkilä <yo@nikoheikkila.fi>"
CMD ["yarn", "run", "dev"]
